name: DevOps / CI Failure Alert

on:
  workflow_run:
    workflows:
      - CI
      - Self Test
      - DevOps / Security
    types: [completed]

jobs:
  alert:
    if: github.event.workflow_run.conclusion == 'failure'
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-workflow-failure-alert.yml@3858e9e74c805067e454740b195372c7195f333b # v1.5.0
    permissions:
      pull-requests: write
